### ISSUE TITLE
Minkunet architecture used in Not All Neighbors Matter

### ISSUE THREAD

**Issue by kimbss470** [SNU-ARC/NotAllNeighborsMatter#1]
Could you provide the specific architecture (#layer, channel size, ...) of MinkUnet that inferred on the Semantickitti dataset? 
Thank you for sharing your valuable work.

**Comment by 99DHL** [comment]
Sorry for the late reply.
We used the same model architecture in SemanticKITTI as in S3DIS and ScanNet.
